matrix:
  include:
  - os: linux
    sudo: required
    python: 2.7
before_install:
- sudo yum check-update -q
install:
- pip install ansible
- |-
  printf '[defaults]
  roles_path = ../' > ansible.cfg
script:
- ansible-playbook -i tests/inventory tests/test.yml --syntax-check
- ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
- ? ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo |
    grep -q 'changed=0.*failed=0' && (echo 'Idempotence test
  : pass' && exit 0) || (echo 'Idempotence test:fail' && exit 1)
- sudo yum repolist |grep -q 'epel' && (echo 'epel is present in yum repolist' &&
  exit 0) || (echo 'epel is not present in yum repolist' && exit 1)
notifications:
  slack:
    secure: YQVL96A/38AWvAHAhIabUNwhNW4Biqdb5tqhgnBJvkmeS4aCzlgabDZPe4nk49wKTxXVDfECn3XQuUzIapFaps0eymW4JGOXF1x7qShj9BjlanqSLfEUqynjnhICPmC9KFDuMivcATMDO6iKU2KaKq6F3PzRIGLDWf6MF3W15bc943FvsFkStmE175gVUIrf/8vpC3aSFj4+TQScrlu3vKFLrUMIpEGCIP21Tkfn3DJZIRY6WuBt/9Izm9rsB6TJ8SkIwI2PUN2ohwv1+/65wF2WRBoO9ZHAroHTr1TADtnTdCjE/SrPadsiH7uLlUsz3Q1Az7pWwgRfmSClmpjujgFlg5GrtZuhFlXFkJxiQFCXKAGtXTmXNxB+/mvMpuwpASi4bfWmL1VeBidOVc7h15R3VMAgnjstbEGQQ0oL/j1uf+5DRwimVqOk1iTHf/Y4MjSUoYaQZsn4gnzxWYe5x2IQOYLfrqA94sGjP6fQmW2C0irQWZXTrytu+Qi5x4ex2FY/FFO8VvVsWdEL/8YsNc9MfyFEYm5nPcl5zOLir0rDJeCq75yFqvbbJBAo87z49z3qRaam+UVvOt8j3RiHMKUD2z3rky4FLK4utpxyQNXxDBcfg56TieK2K/zRzojf1a+nAbPX0aKp+FoMm8dI1Off2K8FXTpZaXoNnnETpMk=
