---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo yum check-update -q

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  # We'll add some commands to test the role here.
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  # Run the role/playbook again, checking to make sure it's idempotent.
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo |grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
  # Request a page via the web server, to make sure it's running and responds.
  - sudo yum repolist |grep -q 'epel' && (echo 'epel is present in yum repolist' && exit 0) || (echo 'epel is not present in yum repolist' && exit 1)
